# Generated by Django 4.2.7 on 2023-11-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='originalvideo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='originalvideotag',
            table=None,
        ),
    ]
