# Generated by Django 4.2.7 on 2023-11-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_rename_youtube_video_id_originalvideo_youtube_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='score_list',
            field=models.TextField(null=True),
        ),
    ]
