# Generated by Django 4.2.7 on 2023-11-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_uservideo_score_alter_uservideo_score_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalvideo',
            name='challenge_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='originalvideo',
            name='video_route',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
