# Generated by Django 4.2.7 on 2023-11-15 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0003_alter_tag_parent_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='likes',
            field=models.ManyToManyField(related_name='like_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservideolikeslog',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
