# Generated by Django 4.2.7 on 2023-11-15 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0004_uservideo_likes_uservideolikeslog_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='like_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
