# Generated by Django 4.2.7 on 2023-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_originalvideo_hits_alter_tag_parent_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalvideo',
            name='video_file_path',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
