# Generated by Django 4.2.7 on 2023-11-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_originalvideo_video_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originalvideo',
            old_name='motion_data_url',
            new_name='motion_data_path',
        ),
    ]
