# Generated by Django 4.2.7 on 2023-11-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_alter_originalvideo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='originalvideotag',
            table='original_video_tag',
        ),
    ]
