# Generated by Django 4.2.7 on 2023-11-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_alter_originalvideo_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalvideo',
            name='channel_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='originalvideo',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='channel_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
