# Generated by Django 4.2.7 on 2023-11-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_alter_originalvideo_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
