# Generated by Django 4.2.7 on 2023-11-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_originalvideo_platform_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
