version: '3.9'

volumes:
  postgres: {}

services:
  postgres:
    container_name: postgres
    image: postgres:16.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dance_dance
      - TZ=Asia/Seoul
    restart: on-failure

  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - POSTGRESQL_HOST=postgres
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure
