version: '3.9'

volumes:
  mysql: {}

services:
  mysql:
    container_name: mysql
    image: mysql:8.1
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dance_dance!10
      - MYSQL_DATABASE=dance_dance
      - MYSQL_USER=dance_dance
      - MYSQL_PASSWORD=dance_dance!10
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    restart: on-failure

  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=mysql
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    restart: on-failure
