# Generated by Django 4.2.7 on 2023-11-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'user_social_provider',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('social_id', models.CharField(max_length=128, null=True, unique=True)),
                ('nickname', models.CharField(max_length=16)),
                ('thumbnail_image_url', models.CharField(max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_agree_privacy', models.BooleanField(default=True)),
                ('is_agree_marketing', models.BooleanField(default=False)),
                ('user_social_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.usersocialprovider')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
