# Generated by Django 4.2.7 on 2023-11-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originalvideo',
            old_name='youtube_video_id',
            new_name='youtube_video_url',
        ),
        migrations.RenameField(
            model_name='uservideo',
            old_name='youtube_video_id',
            new_name='youtube_video_url',
        ),
    ]
